### ISSUE TITLE
Use Vue for all DOM manipulations

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#62]
... and D3 only to perform the necessary calculations. There's now a `better_vue_integration` branch with a rewritten TimelineChart that implements this approach. This is promising and the code is way cleaner, we need a few more steps to ensure this is *finally* the approach we want:

- [x] implements missing feature in NewTimelineChart: axis
- [x] implements missing feature in NewTimelineChart: popover
- [x] make sure data is as reactive as possible (use `watch` instead of `mounted` ?)
- [x] make sure testing works well (see #56)
- [x] explore how this would work for smooth transitions (see #24)
- [x] (nice to have): is it compatible with a canvas approach (#23)

**Comment by peterdesmet** [comment]
Sounds promising

**Comment by niconoe** [comment]
For Canvas: after thinking about it, this approach is probably not better nor worse than the previous one. Nothing impossible if needed, but combining D3, Vue and Canvas will definitely add some layers of complexity. Some challenges being that Vue and D3 are not really made to work outside of the DOM and that the Canvas API is rather rudimentary. The following link may help: https://medium.com/@scottmatthew/using-html-canvas-with-vue-js-493e5ae60887

**Comment by niconoe** [comment]
Approach very successful so far, next step is to convert `VPChart` and `VPIChart` components.

**Comment by niconoe** [comment]
UPDATE: VPChart is done.

**Comment by niconoe** [comment]
UPDATE: VPIChart is done too.

**Comment by niconoe** [comment]
Closing issue. The decision has been taken to continue with this approach.
